[2019-01-17T15:05:43.587] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/text
request client ip:  ::1
request query:  {}
response time: 5
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/filter.js:30:19)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\filter.js:13:191)
    at D:\workspace\koa_project\middlewares\filter.js:13:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\filter.js:13:99
    at D:/workspace/koa_project/middlewares/filter.js:11:5
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/response.js:22:11)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\response.js:9:191)
    at D:\workspace\koa_project\middlewares\response.js:9:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\response.js:9:99
*************** error log end ***************

[2019-01-17T15:23:41.744] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/text
request client ip:  ::1
request query:  {}
response time: 8
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/filter.js:25:19)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\filter.js:13:191)
    at D:\workspace\koa_project\middlewares\filter.js:13:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\filter.js:13:99
    at D:/workspace/koa_project/middlewares/filter.js:11:5
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/response.js:22:11)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\response.js:9:191)
    at D:\workspace\koa_project\middlewares\response.js:9:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\response.js:9:99
*************** error log end ***************

[2019-01-17T15:23:42.261] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/text
request client ip:  ::1
request query:  {}
response time: 1
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/filter.js:25:19)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\filter.js:13:191)
    at D:\workspace\koa_project\middlewares\filter.js:13:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\filter.js:13:99
    at D:/workspace/koa_project/middlewares/filter.js:11:5
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/response.js:22:11)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\response.js:9:191)
    at D:\workspace\koa_project\middlewares\response.js:9:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\response.js:9:99
*************** error log end ***************

[2019-01-17T15:23:42.687] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/text
request client ip:  ::1
request query:  {}
response time: 0
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/filter.js:25:19)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\filter.js:13:191)
    at D:\workspace\koa_project\middlewares\filter.js:13:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\filter.js:13:99
    at D:/workspace/koa_project/middlewares/filter.js:11:5
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/response.js:22:11)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\response.js:9:191)
    at D:\workspace\koa_project\middlewares\response.js:9:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\response.js:9:99
*************** error log end ***************

[2019-01-17T15:53:34.275] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/text
request client ip:  ::1
request query:  {}
response time: 8
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/filter.js:25:19)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\filter.js:13:191)
    at D:\workspace\koa_project\middlewares\filter.js:13:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\filter.js:13:99
    at D:/workspace/koa_project/middlewares/filter.js:11:5
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/response.js:22:11)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\response.js:9:191)
    at D:\workspace\koa_project\middlewares\response.js:9:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\response.js:9:99
*************** error log end ***************

[2019-01-17T15:53:35.060] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/text
request client ip:  ::1
request query:  {}
response time: 1
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/filter.js:25:19)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\filter.js:13:191)
    at D:\workspace\koa_project\middlewares\filter.js:13:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\filter.js:13:99
    at D:/workspace/koa_project/middlewares/filter.js:11:5
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/response.js:22:11)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\response.js:9:191)
    at D:\workspace\koa_project\middlewares\response.js:9:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\response.js:9:99
*************** error log end ***************

[2019-01-17T15:59:18.436] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /vhome_01.jpg
request client ip:  ::1
request query:  {}
response time: 5
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/filter.js:25:19)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\filter.js:13:191)
    at D:\workspace\koa_project\middlewares\filter.js:13:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\filter.js:13:99
    at D:/workspace/koa_project/middlewares/filter.js:11:5
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/response.js:22:11)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\response.js:9:191)
    at D:\workspace\koa_project\middlewares\response.js:9:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\response.js:9:99
*************** error log end ***************

[2019-01-17T15:59:19.281] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /vhome_01.jpg
request client ip:  ::1
request query:  {}
response time: 1
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/filter.js:25:19)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\filter.js:13:191)
    at D:\workspace\koa_project\middlewares\filter.js:13:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\filter.js:13:99
    at D:/workspace/koa_project/middlewares/filter.js:11:5
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/response.js:22:11)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\response.js:9:191)
    at D:\workspace\koa_project\middlewares\response.js:9:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\response.js:9:99
*************** error log end ***************

[2019-01-17T16:04:01.840] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /vhome_01.jpg
request client ip:  ::1
request query:  {}
response time: 7
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/filter.js:25:19)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\filter.js:13:191)
    at D:\workspace\koa_project\middlewares\filter.js:13:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\filter.js:13:99
    at D:/workspace/koa_project/middlewares/filter.js:11:5
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at _callee$ (D:/workspace/koa_project/middlewares/response.js:22:11)
    at tryCatch (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\workspace\koa_project\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\workspace\koa_project\middlewares\response.js:9:191)
    at D:\workspace\koa_project\middlewares\response.js:9:437
    at new Promise (<anonymous>)
    at D:\workspace\koa_project\middlewares\response.js:9:99
*************** error log end ***************

[2019-01-17T16:29:59.163] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/tc
request client ip:  ::1
request query:  {}
response time: 7
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at serve (D:\workspace\koa_project\node_modules\koa-static\index.js:53:15)
*************** error log end ***************

[2019-01-17T16:30:00.193] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/tc
request client ip:  ::1
request query:  {}
response time: 7
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at serve (D:\workspace\koa_project\node_modules\koa-static\index.js:53:15)
*************** error log end ***************

[2019-01-17T16:30:00.555] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/tc
request client ip:  ::1
request query:  {}
response time: 1
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at serve (D:\workspace\koa_project\node_modules\koa-static\index.js:53:15)
*************** error log end ***************

[2019-01-17T16:30:00.782] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/tc
request client ip:  ::1
request query:  {}
response time: 1
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at serve (D:\workspace\koa_project\node_modules\koa-static\index.js:53:15)
*************** error log end ***************

[2019-01-17T16:30:00.948] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/tc
request client ip:  ::1
request query:  {}
response time: 2
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at serve (D:\workspace\koa_project\node_modules\koa-static\index.js:53:15)
*************** error log end ***************

[2019-01-17T16:30:01.141] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/tc
request client ip:  ::1
request query:  {}
response time: 4
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at serve (D:\workspace\koa_project\node_modules\koa-static\index.js:53:15)
*************** error log end ***************

[2019-01-17T16:30:01.338] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/tc
request client ip:  ::1
request query:  {}
response time: 1
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at serve (D:\workspace\koa_project\node_modules\koa-static\index.js:53:15)
*************** error log end ***************

[2019-01-17T16:30:01.610] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/tc
request client ip:  ::1
request query:  {}
response time: 1
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at serve (D:\workspace\koa_project\node_modules\koa-static\index.js:53:15)
*************** error log end ***************

[2019-01-17T16:30:02.602] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/tc
request client ip:  ::1
request query:  {}
response time: 2
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at serve (D:\workspace\koa_project\node_modules\koa-static\index.js:53:15)
*************** error log end ***************

[2019-01-17T16:30:02.828] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/tc
request client ip:  ::1
request query:  {}
response time: 2
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at serve (D:\workspace\koa_project\node_modules\koa-static\index.js:53:15)
*************** error log end ***************

[2019-01-17T16:30:03.010] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/tc
request client ip:  ::1
request query:  {}
response time: 1
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at serve (D:\workspace\koa_project\node_modules\koa-static\index.js:53:15)
*************** error log end ***************

[2019-01-17T16:30:03.178] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/tc
request client ip:  ::1
request query:  {}
response time: 2
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at serve (D:\workspace\koa_project\node_modules\koa-static\index.js:53:15)
*************** error log end ***************

[2019-01-17T16:30:03.370] [ERROR] error - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/tc
request client ip:  ::1
request query:  {}
response time: 2
err name: UnauthorizedError
err message: Authentication Error
err stack: UnauthorizedError: Authentication Error
    at Object.throw (D:\workspace\koa_project\node_modules\koa\lib\context.js:97:11)
    at jwt (D:\workspace\koa_project\node_modules\koa-jwt\lib\index.js:23:22)
    at D:\workspace\koa_project\node_modules\koa-unless\index.js:29:12
    at dispatch (D:\workspace\koa_project\node_modules\koa-compose\index.js:42:32)
    at serve (D:\workspace\koa_project\node_modules\koa-static\index.js:53:15)
*************** error log end ***************

